import './globals.css'
import '../styles/main.scss'

import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import { Footer } from './_components/common/footer'
import { Header } from './_components/common/header'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  )
}
